# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dffc3c1cbd31dd95ea7de68cf4f3d6d9d2ac5bd69cb91b75be0432140b22bfc545e587960ad5792962c04f5ec8cfbabc64df7956483a1a223b188bb12e637d57

test:
  secret_key_base: 6319d21f1e3cbc6d2ccd4e846cff2b2f1db971b0eb98b4f31991411ef61b1930d250e438838369d1946ea4dc28319bf72b6b46c7470c642e5475cbb3ea9b9c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
